Mikescops/git-notify-extension

.github/workflows/node.yml

Add Github Actions to project.

Implement CI checks

---

src/config/config.prod.js
src/options/App.tsx
src/popup/App.tsx

Let user decide which tab to display first

Implement default tab option

---

src/background/pollGitlab.ts
src/background/types.ts
src/background/utils/fetchMRExtraInfo.ts
src/background/utils/getSettings.ts
src/config/config.prod.js
src/options/App.tsx

(Fix): Gitlab CE workaround for approvals

---

src/background/index.ts
src/background/pollGitlab.ts
src/background/types.ts
src/background/utils/fetchMRExtraInfo.ts
src/options/App.tsx
src/popup/App.tsx
src/popup/components/AvatarWithTooltip.tsx
src/popup/components/IssueItem.tsx
src/popup/components/MergeRequest.tsx
src/popup/utils/mergeRequestDownloader.ts

(Feature) Support issues

---

src/popup/components/IssueItem.tsx
src/popup/components/MergeRequest.tsx
src/popup/style.css

1. Fix #11 issue
1. Improve reported issue of author not displayed properly

Enhance display of Merge Requests

---

src/background/setTodoAsDone.ts

Cleared todo tasks were not removed from cache, so on popup relaunch the todo tasks were reappearing.

Remove cleared todo tasks from cache

---

src/popup/App.tsx

Fix display of the progress bar

---

src/popup/App.tsx

Add quicklinks for groups and projects

---

.github/workflows/codeql-analysis.yml

Add code quality CI

---

package-lock.json
package.json
src/background/endpoints/getLatestDataFromGitLab.ts
src/background/endpoints/getLocalData.ts
src/background/types.ts
src/background/utils/fetchMRExtraInfo.ts
src/manifest/common.manifest.json
src/popup/App.tsx
src/popup/components/Content.tsx
src/popup/components/Footer.tsx
src/popup/utils/mergeRequestDownloader.ts

Reviewers on the "To Review" tab

---

src/options/App.tsx

Rework options design

---

src/background/endpoints/getLocalData.ts
src/background/index.ts
src/background/types.ts
src/background/utils/globalError.ts
src/manifest/common.manifest.json
src/popup/App.tsx
src/popup/components/Content.tsx
src/popup/utils/mergeRequestDownloader.ts

Errors are now better served, and locally stored to prevent MV3 error reset.

Improve error handling

---

src/background/endpoints/getMembersOfGroup.ts
src/background/types.ts
src/options/App.tsx
src/options/style.css
src/popup/App.tsx
src/popup/pages/PickReviewer.tsx
src/popup/style.css

Let's give a sense of workload for each group members 👍

Count open PRs on picker

---

package-lock.json
src/background/endpoints/getLocalData.ts
src/popup/App.tsx
src/popup/components/Content.tsx
src/popup/components/Nav.tsx
src/popup/utils/mergeRequestDownloader.ts

Bugfix: Issues did not display

---

src/background/errors.ts
src/background/types.ts
src/background/utils/globalError.ts
src/background/utils/initGitlabApi.ts
src/common/errors.ts
src/options/App.tsx
src/popup/App.tsx
src/popup/components/Content.tsx
src/popup/pages/Onboarding.tsx
src/popup/utils/mergeRequestDownloader.ts

It is difficult for new users to get started with the extension, now it's way easier (and less scary).

New extension onboarding

---

src/popup/components/TodoItem.tsx

fix: Typo in to-do list for general notifications

---

src/background/utils/getSettings.ts
src/config/config.prod.ts
src/options/App.tsx
src/popup/components/Content.tsx

Adds a new option in the settings :eyes: 
Closes #78

Option for Draft in to review tab

---

src/options/App.tsx
src/popup/components/IssueItem.tsx
src/popup/components/MergeRequestItem.tsx
src/popup/components/ProjectName.tsx

Sometimes it was difficult to read the project name

Option to cleanup branch name

---

package-lock.json
package.json
src/popup/components/IssueItem.tsx
src/popup/components/MergeRequestItem.tsx
src/popup/components/ProjectName.tsx
src/popup/components/style.css
src/popup/helpers.ts
src/popup/style.css

Makes it easier to see the content of merge requests and issues.

Display content of issues and MRs

---

src/popup/components/IssueItem.tsx

fix: #96 add missing space in comments label for Issue items

---

src/background/endpoints/getLatestDataFromGitLab.ts
src/background/endpoints/getProjectsList.ts
src/background/utils/initGitlabApi.ts
src/options/App.tsx

Limit requests size and address sensitivity

---

package.json
pnpm-lock.yaml
src/popup/App.tsx
src/popup/components/style.css
src/popup/helpers.ts

Prevent details closing and code escape

---

src/background/endpoints/index.ts
src/background/index.ts
src/common/getLocalData.ts
src/common/globalError.ts
src/popup/App.tsx
src/popup/components/Footer.tsx
src/popup/utils/mergeRequestDownloader.ts
src/popup/utils/ping.ts

- [Fetch content directly from storage instead of ask bg](https://github.com/Mikescops/gitlab-notify-extension/commit/647e03e27e8587efb23ac05ea8eba050afcb0b30)
- [Allow to force refresh content from popup](https://github.com/Mikescops/gitlab-notify-extension/commit/aa9e9bb287bdf536e1a54b2d25e7318b9ac48f54)

Improve content fetching

---

package.json
pnpm-lock.yaml
src/popup/components/Nav.tsx
src/popup/components/style.css
src/popup/style.css

This will allow adding much more content in the future

Rework main navigation

---

src/background/endpoints/getLatestDataFromGitLab.ts
src/background/endpoints/getMembersOfGroup.ts
src/background/endpoints/getProjectsList.ts
src/background/endpoints/index.ts
src/background/endpoints/routine.ts
src/background/endpoints/setTodoAsDone.ts
src/background/index.ts
src/background/utils/initGitlabApi.ts

You can get content for multiple GitLab instances 👍

Fetch data for multiple accounts
